// 帕鲁数据常量
const PAL_DATA = [
  {
    index: "#-1",
    name: "Eye of Cthulhu",
    image_name: "YakushimaBoss001",
    chinese_name: "克苏鲁之眼",
    CombiRank: 1380,
  },
  {
    index: "#-1",
    name: "Illuminant Slime",
    image_name: "YakushimaMonster001_Pink",
    chinese_name: "夜明史莱姆",
    CombiRank: 1500,
  },
  {
    index: "#-1",
    name: "Illuminant Bat",
    image_name: "YakushimaMonster003_Purple",
    chinese_name: "夜明蝙蝠",
    CombiRank: 1250,
  },
  {
    index: "#-1",
    name: "Rainbow Slime",
    image_name: "YakushimaMonster001_Rainbow",
    chinese_name: "彩虹史莱姆",
    CombiRank: 1320,
  },
  {
    index: "#-1",
    name: "Demon Eye",
    image_name: "YakushimaBoss001_Small",
    chinese_name: "恶魔眼",
    CombiRank: 1390,
  },
  {
    index: "#-1",
    name: "Cave Bat",
    image_name: "YakushimaMonster003",
    chinese_name: "洞穴蝙蝠",
    CombiRank: 1340,
  },
  {
    index: "#-1",
    name: "Purple Slime",
    image_name: "YakushimaMonster001_Purple",
    chinese_name: "紫史莱姆",
    CombiRank: 1390,
  },
  {
    index: "#-1",
    name: "Red Slime",
    image_name: "YakushimaMonster001_Red",
    chinese_name: "红史莱姆",
    CombiRank: 1405,
  },
  {
    index: "#-1",
    name: "Green Slime",
    image_name: "YakushimaMonster001",
    chinese_name: "绿史莱姆",
    CombiRank: 1430,
  },
  {
    index: "#-1",
    name: "Blue Slime",
    image_name: "YakushimaMonster001_Blue",
    chinese_name: "蓝史莱姆",
    CombiRank: 1490,
  },
  {
    index: "#-1",
    name: "Enchanted Sword",
    image_name: "YakushimaMonster002",
    chinese_name: "附魔剑",
    CombiRank: 1380,
  },
  {
    index: "#1",
    name: "Lamball",
    image_name: "SheepBall",
    chinese_name: "棉悠悠",
    CombiRank: 1470,
    Priority: 50,
  },
  {
    index: "#2",
    name: "Cattiva",
    image_name: "PinkCat",
    chinese_name: "捣蛋猫",
    CombiRank: 1460,
    Priority: 0,
  },
  {
    index: "#3",
    name: "Chikipi",
    image_name: "ChickenPal",
    chinese_name: "皮皮鸡",
    CombiRank: 1500,
    Priority: 0,
  },
  {
    index: "#4",
    name: "Lifmunk",
    image_name: "Carbunclo",
    chinese_name: "翠叶鼠",
    CombiRank: 1430,
    Priority: 100,
  },
  {
    index: "#5",
    name: "Foxparks",
    image_name: "Kitsunebi",
    chinese_name: "火绒狐",
    CombiRank: 1400,
  },
  {
    index: "#5",
    name: "Foxparks Cryst",
    image_name: "Kitsunebi_Ice",
    chinese_name: "雪绒狐",
    CombiRank: 1305,
  },
  {
    index: "#6",
    name: "Fuack",
    image_name: "BluePlatypus",
    chinese_name: "冲浪鸭",
    CombiRank: 1330,
    Priority: 0,
  },
  {
    index: "#6",
    name: "Fuack Ignis",
    image_name: "BluePlatypus_Fire",
    chinese_name: "热浪鸭",
    CombiRank: 1290,
  },
  {
    index: "#7",
    name: "Sparkit",
    image_name: "ElecCat",
    chinese_name: "伏特喵",
    CombiRank: 1410,
    Priority: 0,
  },
  {
    index: "#8",
    name: "Tanzee",
    image_name: "Monkey",
    chinese_name: "新叶猿",
    CombiRank: 1250,
    Priority: 0,
  },
  {
    index: "#9",
    name: "Rooby",
    image_name: "FlameBambi",
    chinese_name: "燎火鹿",
    CombiRank: 1155,
  },
  {
    index: "#10",
    name: "Pengullet",
    image_name: "Penguin",
    chinese_name: "企丸丸",
    CombiRank: 1350,
    Priority: 0,
  },
  {
    index: "#10",
    name: "Pengullet Lux",
    image_name: "Penguin_Electric",
    chinese_name: "闪丸丸",
    CombiRank: 1310,
  },
  {
    index: "#11",
    name: "Penking",
    image_name: "CaptainPenguin",
    chinese_name: "企丸王",
    CombiRank: 520,
    Priority: 100,
  },
  {
    index: "#11",
    name: "Penking Lux",
    image_name: "CaptainPenguin_Black",
    chinese_name: "闪丸王",
    CombiRank: 490,
  },
  {
    index: "#12",
    name: "Jolthog Cryst",
    image_name: "Hedgehog_Ice",
    chinese_name: "冰刺鼠",
    CombiRank: 1360,
  },
  {
    index: "#12",
    name: "Jolthog",
    image_name: "Hedgehog",
    chinese_name: "電棘鼠",
    CombiRank: 1370,
    Priority: 100,
  },
  {
    index: "#13",
    name: "Gumoss",
    image_name: "PlantSlime",
    chinese_name: "叶泥泥",
    CombiRank: 1240,
    Priority: 0,
  },
  {
    index: "#14",
    name: "Vixy",
    image_name: "CuteFox",
    chinese_name: "玉藻狐",
    CombiRank: 1450,
  },
  {
    index: "#15",
    name: "Hoocrates",
    image_name: "WizardOwl",
    chinese_name: "啼卡尔",
    CombiRank: 1390,
  },
  {
    index: "#16",
    name: "Teafant",
    image_name: "Ganesha",
    chinese_name: "壶小象",
    CombiRank: 1490,
    Priority: 50,
  },
  {
    index: "#17",
    name: "Depresso",
    image_name: "NegativeKoala",
    chinese_name: "瞅什魔",
    CombiRank: 1380,
    Priority: 0,
  },
  {
    index: "#18",
    name: "Cremis",
    image_name: "WoolFox",
    chinese_name: "米露菲",
    CombiRank: 1455,
  },
  {
    index: "#19",
    name: "Daedream",
    image_name: "DreamDemon",
    chinese_name: "寐魔",
    CombiRank: 1230,
    Priority: 33,
  },
  {
    index: "#20",
    name: "Rushoar",
    image_name: "Boar",
    chinese_name: "草莽猪",
    CombiRank: 1130,
    Priority: 100,
  },
  {
    index: "#21",
    name: "Nox",
    image_name: "NightFox",
    chinese_name: "露娜蒂",
    CombiRank: 1180,
    Priority: 0,
  },
  {
    index: "#22",
    name: "Fuddler",
    image_name: "CuteMole",
    chinese_name: "遁地鼠",
    CombiRank: 1220,
    Priority: 66,
  },
  {
    index: "#23",
    name: "Killamari",
    image_name: "NegativeOctopus",
    chinese_name: "勾魂鱿",
    CombiRank: 1290,
    Priority: 100,
  },
  {
    index: "#23",
    name: "Killamari Primo",
    image_name: "NegativeOctopus_Neutral",
    chinese_name: "蚀魂鱿",
    CombiRank: 1250,
  },
  {
    index: "#24",
    name: "Mau Cryst",
    image_name: "Bastet_Ice",
    chinese_name: "冰丝特",
    CombiRank: 1440,
  },
  {
    index: "#24",
    name: "Mau",
    image_name: "Bastet",
    chinese_name: "喵丝特",
    CombiRank: 1480,
    Priority: 100,
  },
  {
    index: "#25",
    name: "Celaray Lux",
    image_name: "FlyingManta_Thunder",
    chinese_name: "雷米儿",
    CombiRank: 830,
  },
  {
    index: "#25",
    name: "Celaray",
    image_name: "FlyingManta",
    chinese_name: "鲁米儿",
    CombiRank: 870,
    Priority: 0,
  },
  {
    index: "#26",
    name: "Direhowl",
    image_name: "Garm",
    chinese_name: "猎狼",
    CombiRank: 1060,
    Priority: 100,
  },
  {
    index: "#27",
    name: "Tocotoco",
    image_name: "ColorfulBird",
    chinese_name: "炸蛋鸟",
    CombiRank: 1340,
    Priority: 100,
  },
  {
    index: "#28",
    name: "Flopie",
    image_name: "FlowerRabbit",
    chinese_name: "波娜兔",
    CombiRank: 1280,
    Priority: 0,
  },
  {
    index: "#29",
    name: "Mozzarina",
    image_name: "CowPal",
    chinese_name: "波霸牛",
    CombiRank: 910,
    Priority: 0,
  },
  {
    index: "#30",
    name: "Bristla",
    image_name: "LittleBriarRose",
    chinese_name: "荊棘魔仙",
    CombiRank: 1320,
    Priority: 100,
  },
  {
    index: "#31",
    name: "Gobfin Ignis",
    image_name: "SharkKid_Fire",
    chinese_name: "红小鲨",
    CombiRank: 1100,
  },
  {
    index: "#31",
    name: "Gobfin",
    image_name: "SharkKid",
    chinese_name: "鲨小子",
    CombiRank: 1090,
    Priority: 100,
  },
  {
    index: "#32",
    name: "Hangyu Cryst",
    image_name: "WindChimes_Ice",
    chinese_name: "冰缚灵",
    CombiRank: 1422,
  },
  {
    index: "#32",
    name: "Hangyu",
    image_name: "WindChimes",
    chinese_name: "吊缚灵",
    CombiRank: 1420,
    Priority: 50,
  },
  {
    index: "#33",
    name: "Mossanda",
    image_name: "GrassPanda",
    chinese_name: "叶胖达",
    CombiRank: 430,
    Priority: 0,
  },
  {
    index: "#33",
    name: "Mossanda Lux",
    image_name: "GrassPanda_Electric",
    chinese_name: "雷胖达",
    CombiRank: 390,
  },
  {
    index: "#34",
    name: "Woolipop",
    image_name: "SweetsSheep",
    chinese_name: "棉花糖",
    CombiRank: 1190,
    Priority: 100,
  },
  {
    index: "#35",
    name: "Caprity",
    image_name: "BerryGoat",
    chinese_name: "灌木羊",
    CombiRank: 930,
    Priority: 50,
  },
  {
    index: "#35",
    name: "Caprity Noct",
    image_name: "BerryGoat_Dark",
    chinese_name: "郁木羊",
    CombiRank: 855,
  },
  {
    index: "#36",
    name: "Melpaca",
    image_name: "Alpaca",
    chinese_name: "美露帕",
    CombiRank: 890,
  },
  {
    index: "#37",
    name: "Eikthyrdeer Terra",
    image_name: "Deer_Ground",
    chinese_name: "祇岳鹿",
    CombiRank: 900,
  },
  {
    index: "#37",
    name: "Eikthyrdeer",
    image_name: "Deer",
    chinese_name: "紫霞鹿",
    CombiRank: 920,
    Priority: 100,
  },
  {
    index: "#38",
    name: "Nitewing",
    image_name: "HawkBird",
    chinese_name: "疾风隼",
    CombiRank: 420,
    Priority: 100,
  },
  {
    index: "#39",
    name: "Ribbuny",
    image_name: "PinkRabbit",
    chinese_name: "姬小兔",
    CombiRank: 1310,
    Priority: 0,
  },
  {
    index: "#39",
    name: "Ribbuny Botan",
    image_name: "PinkRabbit_Grass",
    chinese_name: "艾小兔",
    CombiRank: 1205,
  },
  {
    index: "#40",
    name: "Incineram Noct",
    image_name: "Baphomet_Dark",
    chinese_name: "暗魔羊",
    CombiRank: 580,
  },
  {
    index: "#40",
    name: "Incineram",
    image_name: "Baphomet",
    chinese_name: "炎魔羊",
    CombiRank: 590,
    Priority: 0,
  },
  {
    index: "#41",
    name: "Cinnamoth",
    image_name: "CuteButterfly",
    chinese_name: "幻悦蝶",
    CombiRank: 490,
    Priority: 0,
  },
  {
    index: "#42",
    name: "Arsox",
    image_name: "FlameBuffalo",
    chinese_name: "炽焰牛",
    CombiRank: 790,
    Priority: 100,
  },
  {
    index: "#43",
    name: "Dumud Gild",
    image_name: "LazyCatfish_Gold",
    chinese_name: "梆梆鲶",
    CombiRank: 855,
  },
  {
    index: "#43",
    name: "Dumud",
    image_name: "LazyCatfish",
    chinese_name: "趴趴鲶",
    CombiRank: 895,
    Priority: 100,
  },
  {
    index: "#44",
    name: "Cawgnito",
    image_name: "DarkCrow",
    chinese_name: "黑鸦隐士",
    CombiRank: 1080,
    Priority: 50,
  },
  {
    index: "#45",
    name: "Leezpunk",
    image_name: "LizardMan",
    chinese_name: "朋克蜥",
    CombiRank: 1120,
    Priority: 0,
  },
  {
    index: "#45",
    name: "Leezpunk Ignis",
    image_name: "LizardMan_Fire",
    chinese_name: "热血蜥",
    CombiRank: 1140,
  },
  {
    index: "#46",
    name: "Loupmoon",
    image_name: "Werewolf",
    chinese_name: "月镰魔",
    CombiRank: 950,
    Priority: 100,
  },
  {
    index: "#46",
    name: "Loupmoon Cryst",
    image_name: "Werewolf_Ice",
    chinese_name: "霜镰魔",
    CombiRank: 805,
  },
  {
    index: "#47",
    name: "Galeclaw",
    image_name: "Eagle",
    chinese_name: "天擒鸟",
    CombiRank: 1030,
    Priority: 100,
  },
  {
    index: "#48",
    name: "Robinquill Terra",
    image_name: "RobinHood_Ground",
    chinese_name: "山岳射手",
    CombiRank: 1000,
  },
  {
    index: "#48",
    name: "Robinquill",
    image_name: "RobinHood",
    chinese_name: "羽箭射手",
    CombiRank: 1020,
    Priority: 66,
  },
  {
    index: "#49",
    name: "Gorirat Terra",
    image_name: "Gorilla_Ground",
    chinese_name: "石掌猿",
    CombiRank: 1030,
  },
  {
    index: "#49",
    name: "Gorirat",
    image_name: "Gorilla",
    chinese_name: "铁拳猿",
    CombiRank: 1040,
    Priority: 50,
  },
  {
    index: "#50",
    name: "Beegarde",
    image_name: "SoldierBee",
    chinese_name: "骑士蜂",
    CombiRank: 1070,
    Priority: 0,
  },
  {
    index: "#51",
    name: "Elizabee",
    image_name: "QueenBee",
    chinese_name: "女皇蜂",
    CombiRank: 330,
    Priority: 0,
  },
  {
    index: "#52",
    name: "Grintale",
    image_name: "NaughtyCat",
    chinese_name: "笑魇猫",
    CombiRank: 510,
    Priority: 0,
  },
  {
    index: "#53",
    name: "Swee",
    image_name: "MopBaby",
    chinese_name: "毛掸儿",
    CombiRank: 1300,
    Priority: 100,
  },
  {
    index: "#54",
    name: "Sweepa",
    image_name: "MopKing",
    chinese_name: "毛老爹",
    CombiRank: 410,
    Priority: 50,
  },
  {
    index: "#55",
    name: "Chillet Ignis",
    image_name: "WeaselDragon_Fire",
    chinese_name: "桃旋鼬",
    CombiRank: 790,
  },
  {
    index: "#55",
    name: "Chillet",
    image_name: "WeaselDragon",
    chinese_name: "疾旋鼬",
    CombiRank: 800,
    Priority: 0,
  },
  {
    index: "#56",
    name: "Univolt",
    image_name: "Kirin",
    chinese_name: "雷角马",
    CombiRank: 680,
    Priority: 100,
  },
  {
    index: "#57",
    name: "Foxcicle",
    image_name: "IceFox",
    chinese_name: "吹雪狐",
    CombiRank: 760,
    Priority: 100,
  },
  {
    index: "#58",
    name: "Pyrin",
    image_name: "FireKirin",
    chinese_name: "火麒麟",
    CombiRank: 360,
  },
  {
    index: "#58",
    name: "Pyrin Noct",
    image_name: "FireKirin_Dark",
    chinese_name: "邪麒麟",
    CombiRank: 240,
  },
  {
    index: "#59",
    name: "Reindrix",
    image_name: "IceDeer",
    chinese_name: "严冬鹿",
    CombiRank: 880,
    Priority: 50,
  },
  {
    index: "#60",
    name: "Rayhound",
    image_name: "ThunderDog",
    chinese_name: "霹雳犬",
    CombiRank: 740,
    Priority: 100,
  },
  {
    index: "#61",
    name: "Kitsun Noct",
    image_name: "AmaterasuWolf_Dark",
    chinese_name: "幽焰狼",
    CombiRank: 735,
  },
  {
    index: "#61",
    name: "Kitsun",
    image_name: "AmaterasuWolf",
    chinese_name: "苍焰狼",
    CombiRank: 830,
    Priority: 0,
  },
  {
    index: "#62",
    name: "Dazzi Noct",
    image_name: "RaijinDaughter_Water",
    chinese_name: "天阴童子",
    CombiRank: 1115,
  },
  {
    index: "#62",
    name: "Dazzi",
    image_name: "RaijinDaughter",
    chinese_name: "雷鸣童子",
    CombiRank: 1210,
    Priority: 100,
  },
  {
    index: "#63",
    name: "Lunaris",
    image_name: "Mutant",
    chinese_name: "秘斯媞雅",
    CombiRank: 1110,
    Priority: 100,
  },
  {
    index: "#64",
    name: "Dinossom",
    image_name: "FlowerDinosaur",
    chinese_name: "花冠龙",
    CombiRank: 820,
    Priority: 100,
  },
  {
    index: "#64",
    name: "Dinossom Lux",
    image_name: "FlowerDinosaur_Electric",
    chinese_name: "雷冠龙",
    CombiRank: 810,
  },
  {
    index: "#65",
    name: "Surfent Terra",
    image_name: "Serpent_Ground",
    chinese_name: "流沙蛇",
    CombiRank: 550,
  },
  {
    index: "#65",
    name: "Surfent",
    image_name: "Serpent",
    chinese_name: "滑水蛇",
    CombiRank: 560,
    Priority: 0,
  },
  {
    index: "#66",
    name: "Maraith",
    image_name: "GhostBeast",
    chinese_name: "噬魂兽",
    CombiRank: 1150,
    Priority: 0,
  },
  {
    index: "#67",
    name: "Digtoise",
    image_name: "DrillGame",
    chinese_name: "碎岩龟",
    CombiRank: 850,
    Priority: 100,
  },
  {
    index: "#68",
    name: "Tombat",
    image_name: "CatBat",
    chinese_name: "猫蝠怪",
    CombiRank: 750,
  },
  {
    index: "#69",
    name: "Lovander",
    image_name: "PinkLizard",
    chinese_name: "博爱蜥",
    CombiRank: 940,
    Priority: 0,
  },
  {
    index: "#70",
    name: "Flambelle",
    image_name: "LavaGirl",
    chinese_name: "融焰娘",
    CombiRank: 1405,
  },
  {
    index: "#71",
    name: "Vanwyrm",
    image_name: "BirdDragon",
    chinese_name: "烽歌龙",
    CombiRank: 660,
  },
  {
    index: "#71",
    name: "Vanwyrm Cryst",
    image_name: "BirdDragon_Ice",
    chinese_name: "霜歌龙",
    CombiRank: 620,
  },
  {
    index: "#72",
    name: "Bushi",
    image_name: "Ronin",
    chinese_name: "浪刃武士",
    CombiRank: 640,
    Priority: 100,
  },
  {
    index: "#72",
    name: "Bushi Noct",
    image_name: "Ronin_Dark",
    chinese_name: "鬼刃武士",
    CombiRank: 650,
  },
  {
    index: "#73",
    name: "Beakon",
    image_name: "ThunderBird",
    chinese_name: "迅雷鸟",
    CombiRank: 220,
    Priority: 100,
  },
  {
    index: "#74",
    name: "Ragnahawk",
    image_name: "RedArmorBird",
    chinese_name: "燧火鸟",
    CombiRank: 380,
    Priority: 100,
  },
  {
    index: "#75",
    name: "Katress",
    image_name: "CatMage",
    chinese_name: "暗巫猫",
    CombiRank: 700,
    Priority: 0,
  },
  {
    index: "#75",
    name: "Katress Ignis",
    image_name: "CatMage_Fire",
    chinese_name: "炽巫猫",
    CombiRank: 690,
  },
  {
    index: "#76",
    name: "Wixen Noct",
    image_name: "FoxMage_Dark",
    chinese_name: "幽巫狐",
    CombiRank: 1150,
  },
  {
    index: "#76",
    name: "Wixen",
    image_name: "FoxMage",
    chinese_name: "焰巫狐",
    CombiRank: 1160,
    Priority: 100,
  },
  {
    index: "#77",
    name: "Verdash",
    image_name: "GrassRabbitMan",
    chinese_name: "踏春兔",
    CombiRank: 990,
    Priority: 0,
  },
  {
    index: "#78",
    name: "Vaelet",
    image_name: "VioletFairy",
    chinese_name: "薇莉塔",
    CombiRank: 1050,
    Priority: 0,
  },
  {
    index: "#79",
    name: "Sibelyx",
    image_name: "WhiteMoth",
    chinese_name: "绸笠蛾",
    CombiRank: 450,
  },
  {
    index: "#80",
    name: "Elphidran Aqua",
    image_name: "FairyDragon_Water",
    chinese_name: "水灵龙",
    CombiRank: 530,
  },
  {
    index: "#80",
    name: "Elphidran",
    image_name: "FairyDragon",
    chinese_name: "精灵龙",
    CombiRank: 540,
  },
  {
    index: "#81",
    name: "Kelpsea",
    image_name: "Kelpie",
    chinese_name: "水灵儿",
    CombiRank: 1260,
    Priority: 100,
  },
  {
    index: "#81",
    name: "Kelpsea Ignis",
    image_name: "Kelpie_Fire",
    chinese_name: "火灵儿",
    CombiRank: 1270,
    Priority: 50,
  },
  {
    index: "#82",
    name: "Azurobe Cryst",
    image_name: "BlueDragon_Ice",
    chinese_name: "碧月龙",
    CombiRank: 480,
  },
  {
    index: "#82",
    name: "Azurobe",
    image_name: "BlueDragon",
    chinese_name: "碧海龙",
    CombiRank: 500,
    Priority: 100,
  },
  {
    index: "#83",
    name: "Cryolinx",
    image_name: "WhiteTiger",
    chinese_name: "冰棘兽",
    CombiRank: 130,
    Priority: 66,
  },
  {
    index: "#83",
    name: "Cryolinx Terra",
    image_name: "WhiteTiger_Ground",
    chinese_name: "金棘兽",
    CombiRank: 160,
  },
  {
    index: "#84",
    name: "Blazehowl",
    image_name: "Manticore",
    chinese_name: "狱焰王",
    CombiRank: 710,
    Priority: 100,
  },
  {
    index: "#84",
    name: "Blazehowl Noct",
    image_name: "Manticore_Dark",
    chinese_name: "狱阎王",
    CombiRank: 670,
  },
  {
    index: "#85",
    name: "Relaxaurus",
    image_name: "LazyDragon",
    chinese_name: "佩克龙",
    CombiRank: 280,
    Priority: 100,
  },
  {
    index: "#85",
    name: "Relaxaurus Lux",
    image_name: "LazyDragon_Electric",
    chinese_name: "派克龙",
    CombiRank: 270,
  },
  {
    index: "#86",
    name: "Broncherry Aqua",
    image_name: "SakuraSaurus_Water",
    chinese_name: "海誓龙",
    CombiRank: 840,
  },
  {
    index: "#86",
    name: "Broncherry",
    image_name: "SakuraSaurus",
    chinese_name: "连理龙",
    CombiRank: 860,
    Priority: 50,
  },
  {
    index: "#87",
    name: "Petallia",
    image_name: "FlowerDoll",
    chinese_name: "花丽娜",
    CombiRank: 780,
    Priority: 0,
  },
  {
    index: "#88",
    name: "Reptyro Cryst",
    image_name: "VolcanicMonster_Ice",
    chinese_name: "寒霜兽",
    CombiRank: 230,
  },
  {
    index: "#88",
    name: "Reptyro",
    image_name: "VolcanicMonster",
    chinese_name: "熔岩兽",
    CombiRank: 320,
    Priority: 50,
  },
  {
    index: "#89",
    name: "Kingpaca Cryst",
    image_name: "KingAlpaca_Ice",
    chinese_name: "冰帝美露帕",
    CombiRank: 440,
    Priority: 100,
  },
  {
    index: "#89",
    name: "Kingpaca",
    image_name: "KingAlpaca",
    chinese_name: "君王美露帕",
    CombiRank: 470,
    Priority: 0,
  },
  {
    index: "#90",
    name: "Mammorest",
    image_name: "GrassMammoth",
    chinese_name: "森猛犸",
    CombiRank: 300,
    Priority: 0,
  },
  {
    index: "#90",
    name: "Mammorest Cryst",
    image_name: "GrassMammoth_Ice",
    chinese_name: "雪猛犸",
    CombiRank: 290,
  },
  {
    index: "#91",
    name: "Wumpo",
    image_name: "Yeti",
    chinese_name: "白绒雪怪",
    CombiRank: 460,
    Priority: 100,
  },
  {
    index: "#91",
    name: "Wumpo Botan",
    image_name: "Yeti_Grass",
    chinese_name: "绿苔绒怪",
    CombiRank: 480,
    Priority: 100,
  },
  {
    index: "#92",
    name: "Warsect Terra",
    image_name: "HerculesBeetle_Ground",
    chinese_name: "格鲁力斯",
    CombiRank: 275,
  },
  {
    index: "#92",
    name: "Warsect",
    image_name: "HerculesBeetle",
    chinese_name: "铠格力斯",
    CombiRank: 340,
    Priority: 100,
  },
  {
    index: "#93",
    name: "Fenglope",
    image_name: "FengyunDeeper",
    chinese_name: "云海鹿",
    CombiRank: 980,
    Priority: 50,
  },
  {
    index: "#93",
    name: "Fenglope Lux",
    image_name: "FengyunDeeper_Electric",
    chinese_name: "雷隐鹿",
    CombiRank: 835,
  },
  {
    index: "#94",
    name: "Felbat",
    image_name: "CatVampire",
    chinese_name: "夜幕魔蝠",
    CombiRank: 1010,
    Priority: 33,
  },
  {
    index: "#95",
    name: "Quivern",
    image_name: "SkyDragon",
    chinese_name: "天羽龙",
    CombiRank: 350,
    Priority: 0,
  },
  {
    index: "#95",
    name: "Quivern Botan",
    image_name: "SkyDragon_Grass",
    chinese_name: "翠羽龙",
    CombiRank: 340,
  },
  {
    index: "#96",
    name: "Blazamut Ryu",
    image_name: "KingBahamut_Dragon",
    chinese_name: "殁殃",
    CombiRank: 9,
  },
  {
    index: "#96",
    name: "Blazamut",
    image_name: "KingBahamut",
    chinese_name: "焰煌",
    CombiRank: 10,
    Priority: 0,
  },
  {
    index: "#97",
    name: "Helzephyr",
    image_name: "HadesBird",
    chinese_name: "雷冥鸟",
    CombiRank: 190,
    Priority: 0,
  },
  {
    index: "#97",
    name: "Helzephyr Lux",
    image_name: "HadesBird_Electric",
    chinese_name: "雷鸣鸟",
    CombiRank: 180,
  },
  {
    index: "#98",
    name: "Astegon",
    image_name: "BlackMetalDragon",
    chinese_name: "魔渊龙",
    CombiRank: 150,
    Priority: 33,
  },
  {
    index: "#99",
    name: "Menasting",
    image_name: "DarkScorpion",
    chinese_name: "冥铠蝎",
    CombiRank: 260,
    Priority: 0,
  },
  {
    index: "#99",
    name: "Menasting Terra",
    image_name: "DarkScorpion_Ground",
    chinese_name: "金铠蝎",
    CombiRank: 250,
  },
  {
    index: "#100",
    name: "Anubis",
    image_name: "Anubis",
    chinese_name: "阿努比斯",
    CombiRank: 570,
    Priority: 100,
  },
  {
    index: "#101",
    name: "Jormuntide Ignis",
    image_name: "Umihebi_Fire",
    chinese_name: "腾炎龙",
    CombiRank: 315,
  },
  {
    index: "#101",
    name: "Jormuntide",
    image_name: "Umihebi",
    chinese_name: "覆海龙",
    CombiRank: 310,
    Priority: 100,
  },
  {
    index: "#102",
    name: "Suzaku",
    image_name: "Suzaku",
    chinese_name: "朱雀",
    CombiRank: 50,
    Priority: 100,
  },
  {
    index: "#102",
    name: "Suzaku Aqua",
    image_name: "Suzaku_Water",
    chinese_name: "清雀",
    CombiRank: 30,
  },
  {
    index: "#103",
    name: "Grizzbolt",
    image_name: "ElecPanda",
    chinese_name: "暴电熊",
    CombiRank: 200,
  },
  {
    index: "#104",
    name: "Lyleen",
    image_name: "LilyQueen",
    chinese_name: "百合女王",
    CombiRank: 250,
  },
  {
    index: "#104",
    name: "Lyleen Noct",
    image_name: "LilyQueen_Dark",
    chinese_name: "黑月女王",
    CombiRank: 210,
  },
  {
    index: "#105",
    name: "Faleris Aqua",
    image_name: "Horus_Water",
    chinese_name: "伊西斯",
    CombiRank: 245,
  },
  {
    index: "#105",
    name: "Faleris",
    image_name: "Horus",
    chinese_name: "荷鲁斯",
    CombiRank: 370,
  },
  {
    index: "#106",
    name: "Orserk",
    image_name: "ThunderDragonMan",
    chinese_name: "波鲁杰克斯",
    CombiRank: 140,
  },
  {
    index: "#107",
    name: "Shadowbeak",
    image_name: "BlackGriffon",
    chinese_name: "异构格里芬",
    CombiRank: 60,
  },
  {
    index: "#108",
    name: "Paladius",
    image_name: "SaintCentaur",
    chinese_name: "圣光骑士",
    CombiRank: 80,
  },
  {
    index: "#109",
    name: "Necromus",
    image_name: "BlackCentaur",
    chinese_name: "混沌骑士",
    CombiRank: 70,
  },
  {
    index: "#110",
    name: "Frostallion",
    image_name: "IceHorse",
    chinese_name: "唤冬兽",
    CombiRank: 120,
  },
  {
    index: "#110",
    name: "Frostallion Noct",
    image_name: "IceHorse_Dark",
    chinese_name: "唤夜兽",
    CombiRank: 100,
  },
  {
    index: "#111",
    name: "Jetragon",
    image_name: "JetDragon",
    chinese_name: "空涡龙",
    CombiRank: 90,
  },
  {
    index: "#112",
    name: "Bellanoir",
    image_name: "NightLady",
    chinese_name: "贝菈诺娃",
    CombiRank: 1,
  },
  {
    index: "#112",
    name: "Bellanoir Libero",
    image_name: "NightLady_Dark",
    chinese_name: "贝菈露洁",
    CombiRank: 1,
  },
  {
    index: "#113",
    name: "Selyne",
    image_name: "MoonQueen",
    chinese_name: "辉月伊",
    CombiRank: 345,
  },
  {
    index: "#114",
    name: "Croajiro Noct",
    image_name: "KendoFrog_Dark",
    chinese_name: "极道蛙",
    CombiRank: 765,
  },
  {
    index: "#114",
    name: "Croajiro",
    image_name: "KendoFrog",
    chinese_name: "武道蛙",
    CombiRank: 795,
  },
  {
    index: "#115",
    name: "Lullu",
    image_name: "LeafPrincess",
    chinese_name: "春彩娘",
    CombiRank: 905,
    Priority: 0,
  },
  {
    index: "#116",
    name: "Shroomer",
    image_name: "MushroomDragon",
    chinese_name: "菇咚",
    CombiRank: 720,
    Priority: 0,
  },
  {
    index: "#116",
    name: "Shroomer Noct",
    image_name: "MushroomDragon_Dark",
    chinese_name: "菇波",
    CombiRank: 730,
    Priority: 0,
  },
  {
    index: "#117",
    name: "Kikit",
    image_name: "SmallArmadillo",
    chinese_name: "球犰",
    CombiRank: 1125,
  },
  {
    index: "#118",
    name: "Sootseer",
    image_name: "CandleGhost",
    chinese_name: "恐炬灵",
    CombiRank: 545,
  },
  {
    index: "#119",
    name: "Prixter",
    image_name: "ScorpionMan",
    chinese_name: "蛊刺妖",
    CombiRank: 355,
  },
  {
    index: "#120",
    name: "Knocklem",
    image_name: "WingGolem",
    chinese_name: "泰锋",
    CombiRank: 265,
  },
  {
    index: "#121",
    name: "Yakumo",
    image_name: "GuardianDog",
    chinese_name: "八云犬",
    CombiRank: 945,
  },
  {
    index: "#122",
    name: "Dogen",
    image_name: "SifuDog",
    chinese_name: "汪宗师",
    CombiRank: 665,
    Priority: 100,
  },
  {
    index: "#123",
    name: "Dazemu",
    image_name: "FeatherOstrich",
    chinese_name: "战冠雀",
    CombiRank: 675,
    Priority: 0,
  },
  {
    index: "#124",
    name: "Mimog",
    image_name: "MimicDog",
    chinese_name: "旺财",
    CombiRank: 1200,
  },
  {
    index: "#125",
    name: "Xenovader",
    image_name: "DarkAlien",
    chinese_name: "杰诺贝达",
    CombiRank: 465,
  },
  {
    index: "#126",
    name: "Xenogard",
    image_name: "WhiteAlienDragon",
    chinese_name: "杰诺路达",
    CombiRank: 435,
  },
  {
    index: "#127",
    name: "Xenolord",
    image_name: "DarkMechaDragon",
    chinese_name: "杰诺多兰",
    CombiRank: 265,
  },
  {
    index: "#128",
    name: "Nitemary",
    image_name: "GhostRabbit",
    chinese_name: "魅爱莉",
    CombiRank: 705,
  },
  {
    index: "#129",
    name: "Starryon",
    image_name: "NightBlueHorse",
    chinese_name: "夜冥驹",
    CombiRank: 365,
  },
  {
    index: "#130",
    name: "Silvegis",
    image_name: "WhiteShieldDragon",
    chinese_name: "艾基鲁迦",
    CombiRank: 215,
  },
  {
    index: "#131",
    name: "Smokie",
    image_name: "BlackPuppy",
    chinese_name: "墨丸",
    CombiRank: 1245,
  },
  {
    index: "#132",
    name: "Celesdir",
    image_name: "WhiteDeer",
    chinese_name: "净世鹿",
    CombiRank: 815,
  },
  {
    index: "#133",
    name: "Omascul",
    image_name: "MysteryMask",
    chinese_name: "面惧",
    CombiRank: 630,
    Priority: 0,
  },
  {
    index: "#134",
    name: "Splatterina",
    image_name: "GrimGirl",
    chinese_name: "幽恋娜",
    CombiRank: 725,
  },
  {
    index: "#135",
    name: "Tarantriss",
    image_name: "PurpleSpider",
    chinese_name: "桃蛛娘",
    CombiRank: 825,
  },
  {
    index: "#136",
    name: "Azurmane",
    image_name: "BlueThunderHorse",
    chinese_name: "驭雷马",
    CombiRank: 400,
    Priority: 0,
  },
  {
    index: "#137",
    name: "Bastigor",
    image_name: "SnowTigerBeastman",
    chinese_name: "霜牙王",
    CombiRank: 170,
  },
  {
    index: "#138",
    name: "Prunelia",
    image_name: "BlueberryFairy",
    chinese_name: "梅莉姆",
    CombiRank: 755,
  },
  {
    index: "#139",
    name: "Nyafia",
    image_name: "BadCatgirl",
    chinese_name: "妮瞅莎",
    CombiRank: 645,
    Priority: 100,
  },
  {
    index: "#140",
    name: "Gildane",
    image_name: "GoldenHorse",
    chinese_name: "金驰兽",
    CombiRank: 505,
  },
  {
    index: "#141",
    name: "Herbil",
    image_name: "LeafMomonga",
    chinese_name: "达鼠泥",
    CombiRank: 1445,
  },
  {
    index: "#142",
    name: "Icelyn",
    image_name: "IceWitch",
    chinese_name: "冰姬灵",
    CombiRank: 605,
  },
  {
    index: "#143",
    name: "Frostplume",
    image_name: "SnowPeafowl",
    chinese_name: "白真雪雀",
    CombiRank: 655,
    Priority: 0,
  },
  {
    index: "#144",
    name: "Palumba",
    image_name: "TropicalOstrich",
    chinese_name: "咕咕桑葩",
    CombiRank: 455,
  },
  {
    index: "#145",
    name: "Braloha",
    image_name: "Plesiosaur",
    chinese_name: "梁叶龙",
    CombiRank: 335,
  },
  {
    index: "#146",
    name: "Munchill",
    image_name: "IceCrocodile",
    chinese_name: "肚肚鳄",
    CombiRank: 1335,
  },
  {
    index: "#147",
    name: "Polapup",
    image_name: "IceSeal",
    chinese_name: "香草豹冰",
    CombiRank: 745,
  },
  {
    index: "#148",
    name: "Turtacle",
    image_name: "TentacleTurtle",
    chinese_name: "盔盔仔",
    CombiRank: 1105,
  },
  {
    index: "#148",
    name: "Turtacle Terra",
    image_name: "TentacleTurtle_Ground",
    chinese_name: "金盔仔",
    CombiRank: 1065,
  },
  {
    index: "#149",
    name: "Jellroy",
    image_name: "JellyfishGhost",
    chinese_name: "海月灵",
    CombiRank: 1395,
  },
  {
    index: "#150",
    name: "Jelliette",
    image_name: "JellyfishFairy",
    chinese_name: "海月仙",
    CombiRank: 1385,
  },
  {
    index: "#151",
    name: "Gloopie",
    image_name: "OctopusGirl",
    chinese_name: "墨沫姬",
    CombiRank: 1195,
  },
  {
    index: "#152",
    name: "Finsider",
    image_name: "StuffedShark",
    chinese_name: "布偶鲨",
    CombiRank: 1295,
  },
  {
    index: "#152",
    name: "Finsider Ignis",
    image_name: "StuffedShark_Fire",
    chinese_name: "粉粉布偶鲨",
    CombiRank: 1255,
  },
  {
    index: "#153",
    name: "Ghangler",
    image_name: "GhostAnglerfish",
    chinese_name: "冥灯鱼",
    CombiRank: 525,
  },
  {
    index: "#153",
    name: "Ghangler Ignis",
    image_name: "GhostAnglerfish_Fire",
    chinese_name: "炙灯鱼",
    CombiRank: 505,
  },
  {
    index: "#154",
    name: "Whalaska",
    image_name: "IceNarwhal",
    chinese_name: "凉晶鲸",
    CombiRank: 445,
  },
  {
    index: "#154",
    name: "Whalaska Ignis",
    image_name: "IceNarwhal_Fire",
    chinese_name: "桃晶鲸",
    CombiRank: 430,
  },
  {
    index: "#155",
    name: "Neptilius",
    image_name: "PoseidonOrca",
    chinese_name: "海皇鲸",
    CombiRank: 90,
  },
];
// 特殊配种规则数据
const SPECIAL_BREEDING_RULES = [
  {
    parent1: "Relaxaurus",
    parent2: "Sparkit",
    child: "Relaxaurus Lux",
  },
  {
    parent1: "Incineram",
    parent2: "Maraith",
    child: "Incineram Noct",
  },
  {
    parent1: "Mau",
    parent2: "Pengullet",
    child: "Mau Cryst",
  },
  {
    parent1: "Vanwyrm",
    parent2: "Foxcicle",
    child: "Vanwyrm Cryst",
  },
  {
    parent1: "Eikthyrdeer",
    parent2: "Hangyu",
    child: "Eikthyrdeer Terra",
  },
  {
    parent1: "Elphidran",
    parent2: "Surfent",
    child: "Elphidran Aqua",
  },
  {
    parent1: "Pyrin",
    parent2: "Katress",
    child: "Pyrin Noct",
  },
  {
    parent1: "Mammorest",
    parent2: "Wumpo",
    child: "Mammorest Cryst",
  },
  {
    parent1: "Mossanda",
    parent2: "Grizzbolt",
    child: "Mossanda Lux",
  },
  {
    parent1: "Dinossom",
    parent2: "Rayhound",
    child: "Dinossom Lux",
  },
  {
    parent1: "Jolthog",
    parent2: "Pengullet",
    child: "Jolthog Cryst",
  },
  {
    parent1: "Frostallion",
    parent2: "Helzephyr",
    child: "Frostallion Noct",
  },
  {
    parent1: "Kingpaca",
    parent2: "Reindrix",
    child: "Kingpaca Cryst",
  },
  {
    parent1: "Lyleen",
    parent2: "Menasting",
    child: "Lyleen Noct",
  },
  {
    parent1: "Leezpunk",
    parent2: "Flambelle",
    child: "Leezpunk Ignis",
  },
  {
    parent1: "Blazehowl",
    parent2: "Felbat",
    child: "Blazehowl Noct",
  },
  {
    parent1: "Robinquill",
    parent2: "Fuddler",
    child: "Robinquill Terra",
  },
  {
    parent1: "Broncherry",
    parent2: "Fuack",
    child: "Broncherry Aqua",
  },
  {
    parent1: "Surfent",
    parent2: "Dumud",
    child: "Surfent Terra",
  },
  {
    parent1: "Gobfin",
    parent2: "Rooby",
    child: "Gobfin Ignis",
  },
  {
    parent1: "Suzaku",
    parent2: "Jormuntide",
    child: "Suzaku Aqua",
  },
  {
    parent1: "Reptyro",
    parent2: "Foxcicle",
    child: "Reptyro Cryst",
  },
  {
    parent1: "Hangyu",
    parent2: "Swee",
    child: "Hangyu Cryst",
  },
  {
    parent1: "Mossanda",
    parent2: "Petallia",
    child: "Lyleen",
  },
  {
    parent1: "Vanwyrm",
    parent2: "Anubis",
    child: "Faleris",
  },
  {
    parent1: "Mossanda",
    parent2: "Rayhound",
    child: "Grizzbolt",
  },
  {
    parent1: "Grizzbolt",
    parent2: "Relaxaurus",
    child: "Orserk",
  },
  {
    parent1: "Kitsun",
    parent2: "Astegon",
    child: "Shadowbeak",
  },
  {
    parent1: "Jormuntide",
    parent2: "Blazehowl",
    child: "Jormuntide Ignis",
  },
  {
    parent1: "Bellanoir",
    parent2: "Bellanoir Libero",
    child: "Bellanoir",
  },
  {
    parent1: "Katress",
    parent2: "Wixen",
    child: "Wixen Noct",
    genderSpecific: true,
    parent1Gender: "male",
    parent2Gender: "female",
  },
  {
    parent1: "Katress",
    parent2: "Wixen",
    child: "Katress Ignis",
    genderSpecific: true,
    parent1Gender: "female",
    parent2Gender: "male",
  },
  {
    parent1: "Gorirat",
    parent2: "Kikit",
    child: "Gorirat Terra",
  },
  {
    parent1: "Chillet",
    parent2: "Arsox",
    child: "Chillet Ignis",
  },
  {
    parent1: "Quivern",
    parent2: "Lullu",
    child: "Quivern Botan",
  },
  {
    parent1: "Helzephyr",
    parent2: "Beakon",
    child: "Helzephyr Lux",
  },
  {
    parent1: "Bushi",
    parent2: "Sootseer",
    child: "Bushi Noct",
  },
  {
    parent1: "Menasting",
    parent2: "Knocklem",
    child: "Menasting Terra",
  },
  {
    parent1: "Foxparks",
    parent2: "Foxcicle",
    child: "Foxparks Cryst",
  },
  {
    parent1: "Dazzi",
    parent2: "Omascul",
    child: "Dazzi Noct",
  },
  {
    parent1: "Cryolinx",
    parent2: "Dazemu",
    child: "Cryolinx Terra",
  },
  {
    parent1: "Fenglope",
    parent2: "Azurmane",
    child: "Fenglope Lux",
  },
  {
    parent1: "Caprity",
    parent2: "Tarantriss",
    child: "Caprity Noct",
  },
  {
    parent1: "Loupmoon",
    parent2: "Sweepa",
    child: "Loupmoon Cryst",
  },
  {
    parent1: "Faleris",
    parent2: "Jormuntide",
    child: "Faleris Aqua",
  },
  {
    parent1: "Ribbuny",
    parent2: "Bristla",
    child: "Ribbuny Botan",
  },
  {
    parent1: "Warsect",
    parent2: "Digtoise",
    child: "Warsect Terra",
  },
  {
    parent1: "Kitsun",
    parent2: "Nyafia",
    child: "Kitsun Noct",
  },
  {
    parent1: "Frostallion",
    parent2: "Anubis",
    child: "Bastigor",
  },
  {
    parent1: "Paladius",
    parent2: "Lunaris",
    child: "Selyne",
  },
  {
    parent1: "Gildane",
    parent2: "Eikthyrdeer Terra",
    child: "Celesdir",
  },
  {
    parent1: "Green Slime",
    parent2: "Blue Slime",
    child: "Blue Slime",
  },
  {
    parent1: "Green Slime",
    parent2: "Red Slime",
    child: "Red Slime",
  },
  {
    parent1: "Green Slime",
    parent2: "Purple Slime",
    child: "Purple Slime",
  },
  {
    parent1: "Green Slime",
    parent2: "Illuminant Slime",
    child: "Illuminant Slime",
  },
  {
    parent1: "Green Slime",
    parent2: "Rainbow Slime",
    child: "Rainbow Slime",
  },
  {
    parent1: "Green Slime",
    parent2: "Enchanted Sword",
    child: "Enchanted Sword",
  },
  {
    parent1: "Green Slime",
    parent2: "Cave Bat",
    child: "Rainbow Slime",
  },
  {
    parent1: "Green Slime",
    parent2: "Illuminant Bat",
    child: "Rainbow Slime",
  },
  {
    parent1: "Green Slime",
    parent2: "Eye of Cthulhu",
    child: "Eye of Cthulhu",
  },
  {
    parent1: "Green Slime",
    parent2: "Demon Eye",
    child: "Demon Eye",
  },
  {
    parent1: "Blue Slime",
    parent2: "Red Slime",
    child: "Purple Slime",
  },
  {
    parent1: "Blue Slime",
    parent2: "Purple Slime",
    child: "Purple Slime",
  },
  {
    parent1: "Blue Slime",
    parent2: "Illuminant Slime",
    child: "Illuminant Slime",
  },
  {
    parent1: "Blue Slime",
    parent2: "Rainbow Slime",
    child: "Rainbow Slime",
  },
  {
    parent1: "Blue Slime",
    parent2: "Enchanted Sword",
    child: "Enchanted Sword",
  },
  {
    parent1: "Blue Slime",
    parent2: "Cave Bat",
    child: "Rainbow Slime",
  },
  {
    parent1: "Blue Slime",
    parent2: "Illuminant Bat",
    child: "Rainbow Slime",
  },
  {
    parent1: "Blue Slime",
    parent2: "Eye of Cthulhu",
    child: "Eye of Cthulhu",
  },
  {
    parent1: "Blue Slime",
    parent2: "Demon Eye",
    child: "Demon Eye",
  },
  {
    parent1: "Red Slime",
    parent2: "Purple Slime",
    child: "Purple Slime",
  },
  {
    parent1: "Red Slime",
    parent2: "Illuminant Slime",
    child: "Illuminant Slime",
  },
  {
    parent1: "Red Slime",
    parent2: "Rainbow Slime",
    child: "Rainbow Slime",
  },
  {
    parent1: "Red Slime",
    parent2: "Enchanted Sword",
    child: "Enchanted Sword",
  },
  {
    parent1: "Red Slime",
    parent2: "Cave Bat",
    child: "Rainbow Slime",
  },
  {
    parent1: "Red Slime",
    parent2: "Illuminant Bat",
    child: "Rainbow Slime",
  },
  {
    parent1: "Red Slime",
    parent2: "Eye of Cthulhu",
    child: "Eye of Cthulhu",
  },
  {
    parent1: "Red Slime",
    parent2: "Demon Eye",
    child: "Demon Eye",
  },
  {
    parent1: "Purple Slime",
    parent2: "Illuminant Slime",
    child: "Illuminant Slime",
  },
  {
    parent1: "Purple Slime",
    parent2: "Rainbow Slime",
    child: "Rainbow Slime",
  },
  {
    parent1: "Purple Slime",
    parent2: "Enchanted Sword",
    child: "Enchanted Sword",
  },
  {
    parent1: "Purple Slime",
    parent2: "Cave Bat",
    child: "Illuminant Bat",
  },
  {
    parent1: "Purple Slime",
    parent2: "Illuminant Bat",
    child: "Illuminant Bat",
  },
  {
    parent1: "Purple Slime",
    parent2: "Eye of Cthulhu",
    child: "Eye of Cthulhu",
  },
  {
    parent1: "Purple Slime",
    parent2: "Demon Eye",
    child: "Demon Eye",
  },
  {
    parent1: "Illuminant Slime",
    parent2: "Rainbow Slime",
    child: "Rainbow Slime",
  },
  {
    parent1: "Illuminant Slime",
    parent2: "Enchanted Sword",
    child: "Enchanted Sword",
  },
  {
    parent1: "Illuminant Slime",
    parent2: "Cave Bat",
    child: "Rainbow Slime",
  },
  {
    parent1: "Illuminant Slime",
    parent2: "Illuminant Bat",
    child: "Rainbow Slime",
  },
  {
    parent1: "Illuminant Slime",
    parent2: "Eye of Cthulhu",
    child: "Eye of Cthulhu",
  },
  {
    parent1: "Illuminant Slime",
    parent2: "Demon Eye",
    child: "Demon Eye",
  },
  {
    parent1: "Rainbow Slime",
    parent2: "Enchanted Sword",
    child: "Rainbow Slime",
  },
  {
    parent1: "Rainbow Slime",
    parent2: "Cave Bat",
    child: "Rainbow Slime",
  },
  {
    parent1: "Rainbow Slime",
    parent2: "Illuminant Bat",
    child: "Rainbow Slime",
  },
  {
    parent1: "Rainbow Slime",
    parent2: "Eye of Cthulhu",
    child: "Eye of Cthulhu",
  },
  {
    parent1: "Rainbow Slime",
    parent2: "Demon Eye",
    child: "Demon Eye",
  },
  {
    parent1: "Enchanted Sword",
    parent2: "Cave Bat",
    child: "Enchanted Sword",
  },
  {
    parent1: "Enchanted Sword",
    parent2: "Illuminant Bat",
    child: "Enchanted Sword",
  },
  {
    parent1: "Enchanted Sword",
    parent2: "Eye of Cthulhu",
    child: "Eye of Cthulhu",
  },
  {
    parent1: "Enchanted Sword",
    parent2: "Demon Eye",
    child: "Demon Eye",
  },
  {
    parent1: "Cave Bat",
    parent2: "Illuminant Bat",
    child: "Illuminant Bat",
  },
  {
    parent1: "Cave Bat",
    parent2: "Eye of Cthulhu",
    child: "Eye of Cthulhu",
  },
  {
    parent1: "Cave Bat",
    parent2: "Demon Eye",
    child: "Demon Eye",
  },
  {
    parent1: "Illuminant Bat",
    parent2: "Eye of Cthulhu",
    child: "Eye of Cthulhu",
  },
  {
    parent1: "Illuminant Bat",
    parent2: "Demon Eye",
    child: "Demon Eye",
  },
  {
    parent1: "Eye of Cthulhu",
    parent2: "Demon Eye",
    child: "Eye of Cthulhu",
  },
  {
    parent1: "Killamari",
    parent2: "Ribbuny",
    child: "Killamari Primo",
  },
  {
    parent1: "Pengullet",
    parent2: "Sparkit",
    child: "Pengullet Lux",
  },
  {
    parent1: "Penking",
    parent2: "Rayhound",
    child: "Penking Lux",
  },
  {
    parent1: "Celaray",
    parent2: "Univolt",
    child: "Celaray Lux",
  },
  {
    parent1: "Fuack",
    parent2: "Flambelle",
    child: "Fuack Ignis",
  },
  {
    parent1: "Dumud",
    parent2: "Eikthyrdeer Terra",
    child: "Dumud Gild",
  },
  {
    parent1: "Turtacle",
    parent2: "Digtoise",
    child: "Turtacle Terra",
  },
  {
    parent1: "Croajiro",
    parent2: "Bushi Noct",
    child: "Croajiro Noct",
  },
  {
    parent1: "Azurobe",
    parent2: "Frostplume",
    child: "Azurobe Cryst",
  },
  {
    parent1: "Whalaska",
    parent2: "Chillet Ignis",
    child: "Whalaska Ignis",
  },
  {
    parent1: "Ghangler",
    parent2: "Sootseer",
    child: "Ghangler Ignis",
  },
  {
    parent1: "Finsider",
    parent2: "Gobfin Ignis",
    child: "Finsider Ignis",
  },
  {
    parent1: "Frostallion",
    parent2: "Frostallion",
    child: "Frostallion",
  },
  {
    parent1: "Jetragon",
    parent2: "Jetragon",
    child: "Jetragon",
  },
  {
    parent1: "Paladius",
    parent2: "Paladius",
    child: "Paladius",
  },
  {
    parent1: "Necromus",
    parent2: "Necromus",
    child: "Necromus",
  },
  {
    parent1: "Bellanoir Libero",
    parent2: "Bellanoir Libero",
    child: "Bellanoir Libero",
  },
  {
    parent1: "Blazamut Ryu",
    parent2: "Blazamut Ryu",
    child: "Blazamut Ryu",
  },
  {
    parent1: "Mimog",
    parent2: "Mimog",
    child: "Mimog",
  },
  {
    parent1: "Xenovader",
    parent2: "Xenovader",
    child: "Xenovader",
  },
  {
    parent1: "Xenogard",
    parent2: "Xenogard",
    child: "Xenogard",
  },
  {
    parent1: "Xenolord",
    parent2: "Xenolord",
    child: "Xenolord",
  },
  {
    parent1: "Green Slime",
    parent2: "Green Slime",
    child: "Green Slime",
  },
  {
    parent1: "Cave Bat",
    parent2: "Cave Bat",
    child: "Cave Bat",
  },
  {
    parent1: "Neptilius",
    parent2: "Neptilius",
    child: "Neptilius",
  },
];

// 导出数据供其他模块使用
if (typeof module !== "undefined" && module.exports) {
  module.exports = { PAL_DATA, SPECIAL_BREEDING_RULES };
}
